### ISSUE TITLE
broken links browsing docs at azul3d.org

### ISSUE THREAD

**Issue by Andoryuuta** [azul3d/engine#12]
_From @dskinner on August 4, 2014 22:8_

Consider for example:

http://azul3d.org/native/freetype.v1#package-files

Clicking `context.go` results in the following link

https://github.com/azul3d/native/freetype/blob/v1/context.go

though it should be

https://github.com/azul3d/native-freetype/blob/v1/context.go

that is, `native-freetype`, not `native/freetype`

_Copied from original issue: azul3d/oldissues#6_

**Comment by Andoryuuta** [comment]
_From @slimsag on August 5, 2014 6:54_

Thanks a ton for reporting this!

**Comment by slimsag** [comment]
This should be fixed now with the monorepo change.
