### ISSUE TITLE
Link old wiki pages to new ones.

### ISSUE THREAD

**Issue by Andoryuuta** [azul3d/engine#14]
_From @slimsag on August 7, 2014 21:59_

We should add links on all of the previous wiki pages at http://code.google.com/p/azul3d, so that each one points to the newer, updated version at http://azul3d.org.

This could help people greatly if/when they run across those articles and they don't provide up-to-date information (e.g. in the case of azul3d/issues#7).

_Copied from original issue: azul3d/oldissues#8_

**Comment by Andoryuuta** [comment]
_From @slimsag on August 7, 2014 22:9_

All old wiki pages have been updated to include links to the new ones.

For example, see https://code.google.com/p/azul3d/wiki/LinuxInstall

**Comment by slimsag** [comment]
Stale issue.
