### ISSUE TITLE
Make development version '.tip' or '.dev' instead of '.v0'

### ISSUE THREAD

**Issue by Andoryuuta** [azul3d/engine#16]
_From @slimsag on August 8, 2014 22:55_

People are confused about the intent behind version zero. It would make sense to help new-comers to the project by changing the v0 prefix to .tip or .dev instead.

For example, see someone asking about it in a Hacker News thread: https://news.ycombinator.com/item?id=8151128

Comments regarding the best choice ('tip' vs 'dev') are welcome.

_Copied from original issue: azul3d/oldissues#10_

**Comment by Andoryuuta** [comment]
_From @dskinner on August 8, 2014 23:22_

since adopting the gopkg.in format, I think `.v0` was always geared towards
"nothing is released or stable, this project is immature" as can be read
under the header "Version zero" of http://labix.org/gopkg.in so using `.v0`
for the development branch could likely cause confusion.

I don't really know how you have things setup but if I were to make a
suggestion, running tip would simply be done by not specifying anything. So
instead of `azul3d.org/chippy.v1`, it would just be `azul3d.org/chippy`.

**Comment by Andoryuuta** [comment]
_From @slimsag on August 8, 2014 23:37_

My main fear with using a path like `azul3d.org/chippy` is that it's not obvious that you are using a version that may be broken at any point in time. Tip / development versions might not even compile if there are large significant changes going on, which is what I want the path itself to imply.

`azul3d.org/chippy` looks like any other Go package, and one may assume that it's authors wouldn't break or change much inside it.

You are right about the version zero meaning immature/nothing released yet, it's obvious to me now that my misuse has caused confusion.

Given my explanation above, do you still think `azul3d.org/chippy` would be the best choice?

**Comment by Andoryuuta** [comment]
_From @dskinner on August 9, 2014 0:12_

Actually it'd probably cause problems with the gfx package and subpackages.
At the very least it would look confusing when browsing sources locally if
you had v1 installed and tip in the case that tip was determined by no
suffix on import path. With that said, there probably should be a suffix of
some sort otherwise there'd need to be a different url base to prevent the
said confusion and that's creating unnecessary complications.

.tip or .dev drive the point home either way.

**Comment by Andoryuuta** [comment]
_From @slimsag on August 9, 2014 0:23_

That's a very good point, it would cause confusing conflicts in that way.

Let's go with `azul3d.org/chippy.dev` then. I figure more people understand the term `dev` than `tip`.

**Comment by slimsag** [comment]
No longer using versioning, closing.
