### ISSUE TITLE
Keyboard watcher not receiving keyboard input?

### ISSUE THREAD

**Issue by Firedrake969** [azul3d/engine#161]
On Windows 10, x64

```
watcher := keyboard.NewWatcher()
myNet.AnimateUntilDone(watcher)

func (net *Network) AnimateUntilDone(watcher *keyboard.Watcher) {
    os.Mkdir("frames", 755)
    exit := false
    for !exit {
        fmt.Println(watcher.States())
        exit = watcher.Down(keyboard.Enter)
    }
}
```
The loop never exits even if I do hit enter.  This is the same for `keyboard.A` and other keys that I've tested.
Assume AnimateUntilDone is being called correctly.

**Comment by slimsag** [comment]
Creating a `keyboard.NewWatcher()` doesn't do what you want. It initializes a watcher, but it's not actually going to have its state ever changed (it's a virtual keyboard).

You want to get the watcher from the window, i.e. `window.Keyboard().Down(keyboard.Enter)` because _that keyboard watcher_ will have its state updated (based on window events).

**Comment by Firedrake969** [comment]
Oh, ok...
Is there any way to have a watcher without having a new window?  (I've been searching for a way to have Go listen for keyboard events and this has seemed like the best solution so far)

**Comment by slimsag** [comment]
No; in fact many OSs do not even support getting keyboard events without talking to a window.

That said, you don't need to have a _visible_ window 😉 This example (just take out all the `fmt` calls) shows basically what you want: https://github.com/azul3d/examples/blob/master/azul3d_info/azul3d_info.go

**Comment by Firedrake969** [comment]
Thanks, I'll check that out :)

**Comment by rikonor** [comment]
Hey @slimsag,

I've been trying unsuccessfully to use the example you linked above.
I think that the only way to capture keyboard events is for the window to be in focus, which I don't suppose is possible for an non-visible window.
