### ISSUE TITLE
Add LICENSE file (see https://azul3d.org/doc/license.html)

### ISSUE THREAD

**Issue by AmdHamdani** [azul3d/engine#164]
Hi, I do not see a license in this repository. If you want to make this project to be commercial-friendly and also simple legal, you can choose [MIT](http://choosealicense.com/licenses/mit/) or [Apache](http://choosealicense.com/licenses/apache-2.0/) it's good for very commercial open source project.

**Comment by jayvdb** [comment]
Just a note, there is a lot of licensing discussion in https://github.com/azul3d/engine/issues/30

**Comment by slimsag** [comment]
Hi, the license (same license as Go) is listed on the homepage: https://azul3d.org/doc/license.html

You're correct, we should also have the same license in the root of the project. Not sure how that got lost.
