### ISSUE TITLE
VSync broken in Windows

### ISSUE THREAD

**Issue by slimsag** [azul3d/engine#2]
_From @guregu on August 17, 2015 12:55_

Apparently GLFW silently ignored VSync for certain configurations of Windows until recently, and it's now fixed. Could you please upgrade the included version of GLFW? Using the current master branch solved my problems. 

[engi](https://github.com/ajhager/engi) for example, has a game loop that depends on glfw's vsync.

_Copied from original issue: azul3d/native-glfw#3_

**Comment by slimsag** [comment]
_From @guregu on August 18, 2015 6:28_

This is the fix, I believe: https://github.com/glfw/glfw/commit/8309e0ecb09fe5cf670dff5df1e7ca71821c27bd

**Comment by slimsag** [comment]
I haven't had a chance to look into this yet (I will over the weekend), but we certainly need to release v5 (which will track GLFW C v3.1). From the look of it, that commit is not a part of GLFW v3.1? If so we may have to wait until v3.2 is released.

**Comment by slimsag** [comment]
_From @guregu on August 18, 2015 8:10_

Indeed the fix happened a bit after 3.1.1 was released. I think it might be worth targeting the current glfw master branch for v5, instead of the 3.1 release. Using a dev/unstable branch for it instead of v5 would be okay too. I imagine a lot of people (including me) tested our Windows versions with VSync-forcing graphics cards or non-Aero Windows or something... in its current form engi is completely broken on what is now a very common Windows configuration. 

BTW, I recently sold a game at Comiket 88 using a few azul3d packages, including this and the audio packages. Maybe the first Go game to be physically sold? I'd just like to thank the azul3d team for all the hard work! I'm currently brushing it up and plan to sell it on itch.io or something.

**Comment by slimsag** [comment]
> Indeed the fix happened a bit after 3.1.1 was released. I think it might be worth targeting the current glfw master branch for v5, instead of the 3.1 release. Using a dev/unstable branch for it instead of v5 would be okay too. I imagine a lot of people (including me) tested our Windows versions with VSync-forcing graphics cards or non-Aero Windows or something... in its current form engi is completely broken on what is now a very common Windows configuration.

- There will be a development branch of v3.2 of GLFW located in github.com/go-gl/glfw soon (keep in mind this repo just mirrors my + many other people's work done there, primarily because that repo was NOT versioned until a few months ago).
- Your application _*should not*_ behave differently with vsync on or off. Why do you say it is 'completely broken'? At most you should see screen tearing if vsync is off, but your game should behave the same regardless of frame rate.

> BTW, I recently sold a game at Comiket 88 using a few azul3d packages, including this and the audio packages. Maybe the first Go game to be physically sold? I'd just like to thank the azul3d team for all the hard work! I'm currently brushing it up and plan to sell it on itch.io or something.

This is epic! I'd be really curious to hear more technical details about how you reached this point! And if you wouldn't oppose, we could run a short blog post describing which packages you made use of (both azul and non-azul ones, i.e. glfw and audio packages, engi, etc?) along with maybe a screenshot of the game and a link to it.

**Comment by slimsag** [comment]
_From @guregu on August 21, 2015 5:22_

> There will be a development branch of v3.2 of GLFW located in github.com/go-gl/glfw soon (keep in mind this repo just mirrors my + many other people's work done there, primarily because that repo was NOT versioned until a few months ago).

I see! Sound good. 

> Your application should not behave differently with vsync on or off. Why do you say it is 'completely broken'? At most you should see screen tearing if vsync is off, but your game should behave the same regardless of frame rate.

engi relies on vsync to keep the main loop from running too fast. The only other Go 2d game library I know of, Ebiten, does this too. With vsync disabled, my game ran at like 800 FPS. Theoretically it shouldn't matter how fast your game loop runs if you use the difference in time between the current frame and the last frame in all your calculations.  Maybe because of floating points being weird and 800 FPS being too much, the game ran abnormally fast. 

Do you know of a better way to slow down your main loop without relying on vsync? 

> This is epic! I'd be really curious to hear more technical details about how you reached this point! And if you wouldn't oppose, we could run a short blog post describing which packages you made use of (both azul and non-azul ones, i.e. glfw and audio packages, engi, etc?) along with maybe a screenshot of the game and a link to it.

Thanks! I would be happy to write a blog post. It might take me a couple weeks because I'm working on some major improvements before I release it to the general public.

**Comment by slimsag** [comment]
> Maybe because of floating points being weird and 800 FPS being too much, the game ran abnormally fast.

That's very sad to hear, but I can imagine it's not easy to track down.

> Do you know of a better way to slow down your main loop without relying on vsync?

I don't have time to go into all the details of how to do it yourself, but if you use the [azul3d.org/clock.v1](http://azul3d.org/clock.v1) package it is extremely simple:

```
// Create a new clock
c := clock.New()

func OnEachFrame() {
    // This will pause for a very precisely calculated amount of time to ensure that the game either runs
    // at the monitor refresh rate (vsync) or at an average of ~75FPS (configurable with c.SetMaxFrameRate).
    c.Tick()
}
```

Also provides a method to get difference in time between frames (see `Dt` function) among other things, see [the docs for more](https://godoc.org/azul3d.org/clock.v1#Clock.Dt).

> Thanks! I would be happy to write a blog post. It might take me a couple weeks because I'm working on some major improvements before I release it to the general public.

Sounds awesome! :+1: 

If you want, you can send a PR to the website (https://github.com/azul3d/website) (we just use simple Markdown files) and I could review / provide some feedback for it before publishing. :smile:

**Comment by slimsag** [comment]
This has been fixed. The solution is to import `github.com/go-gl/glfw/v3.1/glfw` instead of the old `azul3d.org/native/glfw.v4/5` package

**Comment by guregu** [comment]
Thanks, I can confirm it works! I still need to write that blog post
